- hosts: webapp
  become: yes
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_message: Hello

  tasks:
    - name: install prerequisites
    apt: 
      name: aptitude 
      update_cache: yes 
      state: latest 
      force_apt_get: yes

  roles:
    - apache2
