- hosts: webapp
  become: yes
  vars:
    - hostname: "webapp"
    - http_port: 80
    - mysql_root_password: "password"
    - mysql_db: "wordpress"
    - mysql_user: "wordpress_user"
    - mysql_password: "password"
  roles:
    - apache2
    - mysql
    - php
    - wordpress
